barberShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('barberapp.urls', namespace='barberapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

barberapp/urls.py
from django.contrib import admin
from django.urls import path

from barberapp.views import BarberappView, ArticleDetailedView, ServicesView, CategoryID, LikeAddView, Services, \
    AppointmentView, MasterViews

app_name = 'barberapp'

urlpatterns = [
    path('', BarberappView.as_view(), name='index'),
    path('post/<int:article_id>/', ArticleDetailedView.as_view(), name='post'),
    path('category/', ServicesView.as_view(), name='categoryes'),
    path('category/<int:category_id>/', CategoryID.as_view(), name='category'),
    path('like/<int:master_id>/', LikeAddView.as_view(), name='like'),
    path('services/<int:master_id>/', Services.as_view(), name='services'),
    path('recording/<int:master_id>/', AppointmentView.as_view(), name='recording'),
    path('masters/', MasterViews.as_view(), name='masters'),
]

barberapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.exceptions import ValidationError
from datetime import datetime, time
# Create your models here.


class Category(models.Model):
    category_name = models.CharField(max_length=50)

    def __str__(self):
        return self.category_name


class Service(models.Model):
    service_name = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        ordering = ('-price',)  # Делаем сортировку по дате публикации
        indexes = (
            models.Index(fields=['-price']),  # Добавляем индексы для ускорения работы с базой данных
        )

    def __str__(self):
        return self.service_name


class Master(models.Model):
    master_name = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField()
    photo = models.ImageField(upload_to='masters/masters_photos')
    rating = models.FloatField()

    def __str__(self):
        return self.master_name


class Appointment(models.Model):
    master = models.ForeignKey(Master, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    comments = models.TextField(null=True, blank=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()

    def clean(self):
        start_time = time(10, 0)  # 10:00 AM
        end_time = time(20, 0)  # 8:00 PM

        if not (start_time <= self.time <= end_time):
            raise ValidationError("Appointment time must be between 10:00 AM and 8:00 PM.")


class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    images = models.ImageField(upload_to='articles/articles_images')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)  # Делаем сортировку по дате публикации
        indexes = (
            models.Index(fields=['-created_at']),  # Добавляем индексы для ускорения работы с базой данных
        )

    def __str__(self):
        return self.title

barberapp/views.py
from django.shortcuts import render
from django.views import View
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponse
from barberapp.models import Article, Service, Category, Master, Appointment
from datetime import datetime, time, timedelta

# Create your views here.


class BarberappView(View):

    def get(self, request):
        articles = Article.objects.all().only('title', 'content', 'images')
        content = {
            'title': 'BarberShop',
            'articles': articles,
        }
        return render(request, 'barberapp/index.html', context=content)


class ArticleDetailedView(View):

    def get(self, request, article_id):
        article = Article.objects.get(id=article_id)
        content = {
            'title': 'post detailed',
            'article': article,
        }
        return render(request, 'barberapp/article_detailed.html', context=content)


class ServicesView(View):

    def get(self, request):
        category = Category.objects.all()
        masters = Master.objects.all()
        content = {
            'title': 'Services',
            'categorys': category,
            'masters': masters,
        }
        return render(request, 'barberapp/categories.html', context=content)


class CategoryID(View):

    def get(self, request, category_id=None):
        if category_id is not None:
            category = Category.objects.get(id=category_id)
            masters = Master.objects.filter(category=category)
        else:
            masters = Master.objects.all()
        content = {
            'title': 'Category',
            'masters': masters,
            'categorys': Category.objects.all(),
        }
        return render(request, 'barberapp/categories.html', context=content)


class LikeAddView(View):
    def get(self, request, master_id):
        master = Master.objects.get(id=master_id)
        master.rating += 1
        master.save()
        return JsonResponse({'like': master.rating})


class Services(View):

    def get(self, request, master_id):
        master = Master.objects.get(id=master_id)
        category = Category.objects.get(master=master)
        services = Service.objects.filter(category=category)
        today = datetime.now().date()

        start_time = time(10, 0)  # 10:00 AM
        end_time = time(20, 0)  # 8:00 PM

        busy_appointments = Appointment.objects.filter(
            master=master,
            date__range=(today, today + timedelta(days=6)),
            time__range=(start_time, end_time)
        )

        # Создаем словарь, где ключ - это день недели, значение - список свободных дат и времени
        available_appointments = {str(today + timedelta(days=day_offset)): [] for day_offset in range(7)}

        for day_offset in range(7):
            current_date = today + timedelta(days=day_offset)
            current_time = datetime.combine(current_date, start_time)

            while current_time.time() <= end_time:
                if not busy_appointments.filter(date=current_date, time=current_time.time()).exists():
                    available_appointments[str(current_date)].append(current_time)
                current_time += timedelta(minutes=30)
        content = {
            'title': 'Services',
            'services': services,
            'master': master,
            'available_appointments': available_appointments
        }
        return render(request, 'barberapp/services.html', context=content)


class AppointmentView(View):

    def get(self, request, master_id):
        master = Master.objects.get(id=master_id)
        services = request.GET.getlist('selected_service')
        client_name = request.GET.get('name')
        phone_number = request.GET.get('phone_number')
        comments = request.GET.get('comments')
        service = Service.objects.get(id=services[0])
        selected_datetime = request.GET.get('selected_datetime')

        if not selected_datetime:
            return HttpResponseBadRequest("Selected datetime is required.")

        date, time = selected_datetime.split(' ')

        # Проверяем, есть ли уже запись на это время
        existing_appointment = Appointment.objects.filter(master=master, date=date, time=time).first()

        if not existing_appointment:
            # Если записи на это время нет, создаем новую
            new_appointment = Appointment.objects.create(master=master, name=client_name, comments=comments,\
                                                         phone_number=phone_number, service=service, date=date, time=time)
            new_appointment.save()
            html_content = f"""
                    <!DOCTYPE html>
                    <html lang="en">
                    <head>
                        <meta charset="UTF-8">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                        <title>Резервирование времени</title>
                        <style>
                            body {{
                                display: flex;
                                align-items: center;
                                justify-content: center;
                                height: 100vh;
                                margin: 0;
                            }}

                            .reservation-info {{
                                text-align: center;
                            }}
                        </style>
                    </head>
                    <body>
                        <div class="reservation-info">
                            <h1>Время зарезервировано</h1>
                            <p>Стрижка: {new_appointment.service.service_name}</p>
                            <p>Время: { new_appointment.date } { new_appointment.time }</p>
                            <p>Мастер: { new_appointment.master.master_name }</p>
                        </div>
                    </body>
                    </html>
                """
            return HttpResponse(html_content)
        else:
            return HttpResponseBadRequest("Appointment already exists for the selected datetime.")


class MasterViews(View):

    def get(self, request):
        masters = Master.objects.all()
        content = {
            'title': 'Masters',
            'masters': masters
        }
        return render(request, 'barberapp/masters.html', context=content)

barberapp/templates/barberapp/appoilment_end.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

barberapp/templates/barberapp/appointment.html
<section data-bs-version="5.1" class="content5 cid-tVTcT2jm4H" id="content5-0">
    <form method="GET" action="{% url 'barberapp:recording' master.id %}" class="appointment-form">
        <div class="form-group">
            <label for="name">Имя:</label>
            <input type="text" name="name" required>
        </div>

        <div class="form-group">
            <label for="phone_number">Номер телефона:</label>
            <input type="text" name="phone_number" required>
        </div>

        <div class="form-group">
            <label for="comments">Комментарий:</label>
            <textarea name="comments"></textarea>
        </div>

        <div class="form-group">
            <label for="selected_date">Выберите дату и время:</label>
            <select name="selected_datetime" id="selected_datetime">
                {% for date, appointments in available_appointments.items %}
                    {% for appointment in appointments %}
                        <option value="{{ date }} {{ appointment|time:'H:i' }}">{{ date }} {{ appointment|time:'H:i' }}</option>
                    {% endfor %}
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="selected_service">Выберите сервис:</label>
            <select name="selected_service" id="selected_service">
                {% for service in services %}
                    <option value="{{ service.id }}">{{ service.service_name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <button type="submit">Записаться</button>
        </div>
    </form>
</section>

barberapp/templates/barberapp/article_detailed.html
{% extends 'barberapp/base.html' %}
{% load static %}
{% block title %}
{{ title }}
{% endblock %}
{% block css %}
  <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons2/mobirise2.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="preload" href="https://fonts.googleapis.com/css?family=Inter+Tight:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter+Tight:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"></noscript>
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">
{% endblock %}
{% block content %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
<section data-bs-version="5.1" class="header5 cid-tVTvPJRa4p" id="header05-3">
	<div class="topbg"></div>
	<div class="align-center container">
		<div class="row justify-content-center">
			<div class="col-md-12 content-head">
				<h1 class="mbr-section-title mbr-fonts-style mb-4 display-2">
					<strong>{{ article.title }}</strong>
				</h1>
			</div>
		</div>
		<div class="row mt-5 justify-content-center">
			<div class="col-12 col-lg-7">
				<img src="{{ article.images.url }}" alt="Mobirise Website Builder" title="">
			</div>
		</div>
	</div>
</section>

<section data-bs-version="5.1" class="article12 cid-tVTvRHVt0Y" id="article12-4" style="alignment-baseline: auto">
    
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <p class="mbr-text mbr-fonts-style display-7">
                {{ article.content }}
                </p>
            </div>
        </div>
    </div>
</section><section class="display-7" style="padding: 0;align-items: center;justify-content: center;flex-wrap: wrap;    align-content: center;display: flex;position: relative;height: 4rem;"><a href="https://mobiri.se/771791" style="flex: 1 1;height: 4rem;position: absolute;width: 100%;z-index: 1;"><img alt="" style="height: 4rem;" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="></a><p style="margin: 0;text-align: center;" class="display-7">&#8204;</p><a style="z-index:1" href="https://mobirise.com/builder/html-code-generator.html">HTML Code Creator</a></section><script src="{% static 'assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>  <script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>  <script src="{% static 'assets/ytplayer/index.js' %}"></script>  <script src="{% static 'assets/dropdown/js/navbar-dropdown.js' %}"></script>  <script src="{% static 'assets/theme/js/script.js' %}"></script>
  
{% endblock %}

barberapp/templates/barberapp/base.html
{% load static %}

<!DOCTYPE html>
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v5.9.6, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v5.9.6, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'assets/images/logo2.png' %}" type="image/x-icon">
  <meta name="description" content="">


  <title>Home</title>
  <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons2/mobirise2.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/socicon/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="preload" href="https://fonts.googleapis.com/css?family=Inter+Tight:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter+Tight:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"></noscript>
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">
  <style>
      .appointment-form {
        max-width: 400px;
        margin: 0 auto;
    }

    .form-group {
        margin-bottom: 15px;
    }

    label {
        display: block;
        margin-bottom: 5px;
    }
  </style>


</head>
<body>


  <section data-bs-version="5.1" class="menu menu4 cid-tVTpHKrb8m" once="menu" id="menu04-1">


	<nav class="navbar navbar-dropdown navbar-expand-lg">
		<div class="container">
			<div class="navbar-brand">


			</div>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
				<div class="hamburger">
					<span></span>
					<span></span>
					<span></span>
					<span></span>
				</div>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav nav-dropdown navbar-nav-top-padding" data-app-modern-menu="true"><li class="nav-item">
						<a class="nav-link link text-secondary display-4" href="{% url 'barberapp:index' %}">Premium</a>
					</li>
					<li class="nav-item">
						<a class="nav-link link show text-secondary display-4" href="{% url 'barberapp:categoryes' %}" aria-expanded="false">Услуги</a>
					</li>
					<li class="nav-item">
						<a class="nav-link link text-secondary display-4" href="{% url 'barberapp:masters' %}">Мастера</a>
					</li></ul>

				<div class="navbar-buttons mbr-section-btn"><a class="btn btn-secondary display-4" href="https://mobiri.se">Get Started!</a></div>
			</div>
		</div>
	</nav>
</section>
{% block content %}

{% endblock %}
</body>
</html>

barberapp/templates/barberapp/categories.html
{% extends 'barberapp/base.html' %}
{% load static %}
{% block title %}
{{ title }}
{% endblock %}
{% block css %}
  <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons2/mobirise2.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="preload" href="https://fonts.googleapis.com/css?family=Inter+Tight:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter+Tight:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"></noscript>
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">
{% endblock %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<section data-bs-version="5.1" class="features3 cid-tVTBh11JgO" id="features3-7">
    <div class="container">
        <div class="mbr-section-head">
            <h4 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                <strong>Features</strong></h4>
            <h5 class="mbr-section-subtitle mbr-fonts-style align-center mb-0 mt-2 display-5">To add more cards, hover on a card and
                click 'Add items'</h5>
        </div>
        <div class="row mt-4">
        <div class="item features-image col-12 col-md-6 col-lg-4 mb-4">
            <div class="item-wrapper">
                <div class="item-content">
                    <h5 class="item-title mbr-fonts-style display-7"><strong>Все мастера</strong></h5>
                </div>
                <div class="mbr-section-btn item-footer mt-2">
                    <a href="{% url 'barberapp:categoryes' %}" class="btn btn-primary item-btn display-7" target="_blank">Learn More &gt;</a>
                </div>
            </div>
        </div>
        {% for category in categorys %}
            <div class="item features-image col-12 col-md-6 col-lg-4 mb-4">
                <div class="item-wrapper">
                    <div class="item-content">
                        <h5 class="item-title mbr-fonts-style display-7"><strong>{{ category.category_name }}</strong></h5>
                    </div>
                    <div class="mbr-section-btn item-footer mt-2">
                        <a href="{% url 'barberapp:category' category.id %}" class="btn btn-primary item-btn display-7" target="_blank">Learn More &gt;</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</section>
<section data-bs-version="5.1" class="team2 cid-tVTcT2jm4H" xmlns="http://www.w3.org/1999/html" id="team2-0">

{% for master in masters %}
    <a href="{% url 'barberapp:services' master.id %}">
        <div class="container">
            <div class="item features-image">
                <div class="item-wrapper">
                    <div class="row align-items-center">
                        <div class="col-12 col-md-4">
                            <div class="image-wrapper">
                                <img src="{{ master.photo.url }}" alt="Mobirise Website Builder">
                            </div>
                        </div>
                        <div class="col-12 col-md">
                            <div class="card-box">
                                <h5 class="card-title mbr-fonts-style m-0 mb-3 display-5">
                                    <strong>{{ master.master_name }}</strong>
                                </h5>
                                <p class="mbr-text mbr-fonts-style display-7">
                                    {{ master.master_description }}
                                </p>
                                <p class="mbr-text mbr-fonts-style display-7">
                                    Likes: <span id="like-count-{{ master.id }}">{{ master.rating }}</span>
                                </p>
                                <div>
                                    <button type="button" class="btn like-button" data-master-id="{{ master.id }}">Like</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </a>
{% endfor %}
</section>
<script>
    // Обработчик события нажатия кнопки "Like"
    document.querySelectorAll('.like-button').forEach(function(button) {
      button.addEventListener('click', function(event) {
        event.preventDefault();

        var masterId = this.dataset.masterId;
        var xhr = new XMLHttpRequest();
        xhr.open('GET', '/like/' + masterId + '/');
        xhr.onreadystatechange = function() {
          if (xhr.readyState === XMLHttpRequest.DONE) {
            if (xhr.status === 200) {
              // Обновляем отображение количества лайков
              var likeCountElement = document.querySelector('#like-count-' + masterId);
              // Парсим JSON и получаем значение like_count
              var responseJson = JSON.parse(xhr.responseText);
              console.log(xhr.responseText);
              var updatedLikeCount = responseJson.like;
              likeCountElement.innerHTML = updatedLikeCount;
            } else {
              console.error('Произошла ошибка при отправке AJAX-запроса');
            }
          }
        };
        xhr.send();
      });
    });
</script>
{% endblock %}

barberapp/templates/barberapp/index.html
{% extends 'barberapp/base.html' %}
{% load static %}
{% block title %}
{{ title }}
{% endblock %}
{% block css %}
      <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
      <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
      <link rel="stylesheet" href="{% static 'assets/socicon/css/styles.css' %}">
      <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
      <link rel="preload" href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;700&display=swap&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
      <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;700&display=swap&display=swap"></noscript>
      <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">

{% endblock %}
{% block content %}
<section data-bs-version="5.1" class="team2 cid-tVTcT2jm4H" xmlns="http://www.w3.org/1999/html" id="team2-0">
    {% for article in articles %}
        <a href="{% url 'barberapp:post' article.id %}">
            <div class="container">
                <div class="item features-image">
                    <div class="item-wrapper">
                        <div class="row align-items-center">
                            <div class="col-12 col-md-4">
                                <div class="image-wrapper">
                                    <img src="{{ article.images.url }}" alt="Mobirise Website Builder">
                                </div>
                            </div>
                            <div class="col-12 col-md">
                                <div class="card-box">
                                    <h5 class="card-title mbr-fonts-style m-0 mb-3 display-5">
                                        <strong>{{ article.title }}</strong>
                                    </h5>
                                    <p class="mbr-text mbr-fonts-style display-7">
                                        {{ article.content }}
                                    </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    {% endfor %}
</section><section class="display-7" style="padding: 0;align-items: center;justify-content: center;flex-wrap: wrap;    align-content: center;display: flex;position: relative;height: 4rem;"><a href="https://mobiri.se/771791" style="flex: 1 1;height: 4rem;position: absolute;width: 100%;z-index: 1;"><img alt="" style="height: 4rem;" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="></a><p style="margin: 0;text-align: center;" class="display-7">&#8204;</p><a style="z-index:1" href="https://mobirise.com/offline-website-builder.html">Offline Website Maker</a></section><script src="{% static 'assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>  <script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>  <script src="{% static 'assets/ytplayer/index.js' %}"></script>  <script src="{% static 'assets/theme/js/script.js' %}"></script>


{% endblock %}

barberapp/templates/barberapp/services.html
{% extends 'barberapp/base.html' %}
{% load static %}
{% block title %}
{{ title }}
{% endblock %}
{% block css %}
  <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons2/mobirise2.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="preload" href="https://fonts.googleapis.com/css?family=Inter+Tight:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter+Tight:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"></noscript>
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">
{% endblock %}
{% block content %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
<section data-bs-version="5.1" class="features3 cid-sTq7hCfJ2e" id="features3-3">
        <div class="container">
            <div class="mbr-section-head">
                <h4 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                    <strong>{{ master.master_name }}</strong></h4>
                <h5 class="mbr-section-subtitle mbr-fonts-style align-center mb-0 mt-2 display-5">{{ master.description }}</h5>
            </div>
            <div class="row mt-4">
                {% for service in master.category.service_set.all %}

                    <div class="item features-image сol-12 col-md-6 col-lg-4">
                        <div class="item-wrapper">
                            <div class="item-content">
                                <h5 class="item-title mbr-fonts-style display-7"><strong>{{ service.category.category_name }}</strong></h5>

                                <p class="mbr-text mbr-fonts-style mt-3 display-7">{{ service.service_name }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
</section>
    {% include 'barberapp/appointment.html' %}
{% endblock %}